<?php
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__.'/../config.php';
if(!isset($_SESSION['userId'])||($_SESSION['userRole']??'')==='pensioner'){http_response_code(403);echo json_encode(['success'=>false,'message'=>'Access denied']);exit;}
ensurePensionBeneficiaryTables($conn);
ensureStaffDueExtendedColumns($conn);
if($_SERVER['REQUEST_METHOD']==='GET'){$ipps=trim((string)($_GET['deceased_ipps_no']??''));$staffId=(int)($_GET['staffdue_id']??0);$registryId=(int)($_GET['registry_id']??0);if($ipps===''&&$staffId<1&&$registryId<1){echo json_encode(['success'=>false,'message'=>'An officer or pensioner reference is required.']);exit;}$stmt=$conn->prepare('SELECT * FROM tb_pension_beneficiaries WHERE (deceased_ipps_no=? OR deceased_staffdue_id=? OR deceased_registry_id=?) AND is_active=1 ORDER BY is_primary DESC,beneficiary_id');$stmt->bind_param('sii',$ipps,$staffId,$registryId);$stmt->execute();echo json_encode(['success'=>true,'records'=>$stmt->get_result()->fetch_all(MYSQLI_ASSOC)]);exit;}
$p=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($p['beneficiary_id']??0);$action=strtolower(trim((string)($p['action']??'save')));
if($action==='delete'){if($id<1){echo json_encode(['success'=>false,'message'=>'Invalid beneficiary']);exit;}$stmt=$conn->prepare('UPDATE tb_pension_beneficiaries SET is_active=0,updated_at=NOW() WHERE beneficiary_id=?');$stmt->bind_param('i',$id);$ok=$stmt->execute();echo json_encode(['success'=>$ok,'message'=>$ok?'Beneficiary removed.':$stmt->error]);exit;}
$staffId=(int)($p['deceased_staffdue_id']??0);$registryId=(int)($p['deceased_registry_id']??0);$ipps=trim((string)($p['deceased_ipps_no']??''));if($staffId<1&&$registryId<1&&$ipps===''){echo json_encode(['success'=>false,'message'=>'Select the related deceased officer or pensioner.']);exit;}
foreach(['first_name','last_name','beneficiary_nin'] as $field){if(trim((string)($p[$field]??''))===''){echo json_encode(['success'=>false,'message'=>ucwords(str_replace('_',' ',$field)).' is required.']);exit;}}
$gender=trim((string)($p['gender']??''));$nin=validateNationalIdNumber((string)$p['beneficiary_nin'],null,$gender!==''?$gender:null);if(!$nin['valid']){echo json_encode(['success'=>false,'message'=>$nin['message']??'Beneficiary NIN is invalid.']);exit;}$p['beneficiary_nin']=$nin['normalized'];
$telephone=trim((string)($p['telephone']??''));if($telephone!==''&&($telephone=normalizePhoneNumber($telephone))===null){echo json_encode(['success'=>false,'message'=>'Beneficiary phone number is invalid.']);exit;}
$profile=null;if($staffId>0){$s=$conn->prepare('SELECT retirementType,retirementDate,dateOfDeath,livingStatus FROM tb_staffdue WHERE id=? LIMIT 1');$s->bind_param('i',$staffId);$s->execute();$profile=$s->get_result()->fetch_assoc();$s->close();}elseif($registryId>0){$s=$conn->prepare('SELECT retirementType,retirementDate,dateOfDeath,livingStatus,COALESCE(NULLIF(ippsNo,\'\'),computerNo) ippsNo FROM tb_fileregistry WHERE id=? LIMIT 1');$s->bind_param('i',$registryId);$s->execute();$profile=$s->get_result()->fetch_assoc();$s->close();if($ipps===''&&$profile)$ipps=(string)$profile['ippsNo'];}
$isDeceased=$profile&&(strtolower(trim((string)($profile['livingStatus']??'')))==='deceased'||normalizeBenefitsRetirementTypeKey((string)($profile['retirementType']??''))==='death');$conditional=['beneficiary_ipps_no','beneficiary_supplier_no','administration_reference','bank_name','bank_account','bank_branch'];if(!$isDeceased)foreach($conditional as $field)$p[$field]='';$earning=calculateBeneficiaryEarningPeriod($profile['retirementDate']??null,$profile['dateOfDeath']??null,normalizeBenefitsRetirementTypeKey((string)($profile['retirementType']??''))==='death');
$values=['deceased_staffdue_id'=>$staffId,'deceased_registry_id'=>$registryId,'deceased_ipps_no'=>$ipps,'beneficiary_type'=>trim((string)($p['beneficiary_type']??'administrator')),'first_name'=>trim((string)$p['first_name']),'middle_name'=>trim((string)($p['middle_name']??'')),'last_name'=>trim((string)$p['last_name']),'gender'=>$gender,'beneficiary_nin'=>$p['beneficiary_nin'],'beneficiary_ipps_no'=>trim((string)($p['beneficiary_ipps_no']??'')),'beneficiary_supplier_no'=>trim((string)($p['beneficiary_supplier_no']??'')),'telephone'=>$telephone??'','email'=>trim((string)($p['email']??'')),'relationship_to_deceased'=>trim((string)($p['relationship_to_deceased']??'')),'administration_reference'=>trim((string)($p['administration_reference']??'')),'earning_start_date'=>$isDeceased?(string)($profile['dateOfDeath']??''):'','earning_end_date'=>$isDeceased?(string)($earning['expiry_date']??''):'','earning_basis_date'=>$isDeceased?(string)($earning['basis_date']??''):'','earning_expiry_date'=>$isDeceased?(string)($earning['expiry_date']??''):'','last_earning_month'=>$isDeceased?(string)($earning['last_earning_month']??''):'','earning_period_label'=>$isDeceased?(string)($earning['remaining_label']??''):'','bank_name'=>trim((string)($p['bank_name']??'')),'bank_account'=>trim((string)($p['bank_account']??'')),'bank_branch'=>trim((string)($p['bank_branch']??'')),'is_primary'=>!empty($p['is_primary'])?1:0,'notes'=>trim((string)($p['notes']??''))];
$columns=array_keys($values);$params=array_values($values);$types='';foreach($columns as $column)$types.=in_array($column,['deceased_staffdue_id','deceased_registry_id','is_primary'],true)?'i':'s';if($id>0){$sets=implode('=?,',$columns).'=?';$sql='UPDATE tb_pension_beneficiaries SET '.$sets.',updated_at=NOW() WHERE beneficiary_id=?';$params[]=$id;$types.='i';}else{$columns[]='created_by';$params[]=(string)$_SESSION['userId'];$types.='s';$sql='INSERT INTO tb_pension_beneficiaries ('.implode(',',$columns).') VALUES ('.implode(',',array_fill(0,count($columns),'?')).')';}
$stmt=$conn->prepare($sql);$stmt->bind_param($types,...$params);$ok=$stmt->execute();echo json_encode(['success'=>$ok,'message'=>$ok?'Beneficiary details saved.':$stmt->error,'beneficiary_id'=>$id?:$conn->insert_id]);
