<?php
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__ . '/../config.php';
if(session_status()===PHP_SESSION_NONE)session_start();
if(!isset($_SESSION['userId'])||strtolower(trim((string)($_SESSION['userRole']??'')))==='pensioner'){http_response_code(403);echo json_encode(['success'=>false,'message'=>'Access denied']);exit;}
ensurePayrollManagementTables($conn);$cycleId=(int)($_GET['cycle_id']??0);if($cycleId<=0){http_response_code(422);echo json_encode(['success'=>false,'message'=>'Cycle ID is required']);exit;}
$summaries=[];$stmt=$conn->prepare('SELECT source_section,reported_count,extracted_count,reported_appeared_amount,extracted_appeared_amount,reported_payable_amount,extracted_payable_amount,validation_status,validation_note FROM tb_payroll_section_summaries WHERE cycle_id=? ORDER BY section_summary_id');$stmt->bind_param('i',$cycleId);$stmt->execute();$r=$stmt->get_result();while($row=$r->fetch_assoc())$summaries[]=$row;$stmt->close();
$classified=[];$stmt=$conn->prepare("SELECT classified_entry_id,source_section,source_sheet,source_row_number,supplierNo,beneficiary_name,invoice_number,appeared_amount,payable_amount,recovery_amount,reason,matched_regNo,review_status FROM tb_payroll_classified_entries WHERE cycle_id=? ORDER BY FIELD(review_status,'Pending Review','Observed','Approved','Rejected'),classified_entry_id LIMIT 500");$stmt->bind_param('i',$cycleId);$stmt->execute();$r=$stmt->get_result();while($row=$r->fetch_assoc())$classified[]=$row;$stmt->close();
$paymentSummary=[];$stmt=$conn->prepare('SELECT reconciliation_status,COUNT(*) AS total,COALESCE(SUM(amount_paid),0) AS amount_paid,COALESCE(SUM(amount_variance),0) AS variance FROM tb_payroll_payment_register_entries WHERE cycle_id=? GROUP BY reconciliation_status');$stmt->bind_param('i',$cycleId);$stmt->execute();$r=$stmt->get_result();while($row=$r->fetch_assoc())$paymentSummary[]=$row;$stmt->close();
$paymentExceptions=[];$stmt=$conn->prepare("SELECT register_entry_id,supplierNo,supplier_name,invoice_number,payment_date,amount_paid,eft_number,bank_name,account_number_masked,matched_regNo,reconciliation_status,amount_variance,match_confidence,review_status,review_note,source_page FROM tb_payroll_payment_register_entries WHERE cycle_id=? AND (reconciliation_status<>'Paid in Full' OR review_status='Needs Review') ORDER BY register_entry_id LIMIT 500");$stmt->bind_param('i',$cycleId);$stmt->execute();$r=$stmt->get_result();while($row=$r->fetch_assoc())$paymentExceptions[]=$row;$stmt->close();
echo json_encode(['success'=>true,'section_summaries'=>$summaries,'classified_entries'=>$classified,'payment_summary'=>$paymentSummary,'payment_exceptions'=>$paymentExceptions]);$conn->close();
