<?php
header('Content-Type: application/json; charset=utf-8'); require_once __DIR__.'/../config.php'; if(session_status()===PHP_SESSION_NONE)session_start();
if(!isset($_SESSION['userId'])||strtolower(trim((string)($_SESSION['userRole']??'')))==='pensioner'){http_response_code(403);echo json_encode(['success'=>false,'message'=>'Access denied']);exit;} ensurePayrollManagementTables($conn);
function bindPayrollHistoryParams(mysqli_stmt $stmt,string $types,array $params):void{if($types==='')return;$refs=[];foreach($params as $key=>$value){$refs[$key]=&$params[$key];}$stmt->bind_param($types,...$refs);}
$kind=($_GET['kind']??'rows')==='cycles'?'cycles':'rows';$status=trim((string)($_GET['status']??'all'));$page=max(1,(int)($_GET['page']??1));$limit=min(100,max(10,(int)($_GET['limit']??20)));$search=trim((string)($_GET['search']??''));$year=(int)($_GET['year']??0);$month=(int)($_GET['month']??0);$fy=trim((string)($_GET['financial_year']??''));$quarter=trim((string)($_GET['quarter']??''));
$where=' WHERE COALESCE(c.is_deleted,0)=0';$types='';$params=[];
if($year>=2000){$where.=' AND c.payroll_year=?';$types.='i';$params[]=$year;}if($month>=1&&$month<=12){$where.=' AND c.payroll_month=?';$types.='i';$params[]=$month;}if($fy!==''){$where.=' AND c.financial_year_label=?';$types.='s';$params[]=$fy;}if(in_array($quarter,['Q1','Q2','Q3','Q4'],true)){$where.=' AND c.quarter_label=?';$types.='s';$params[]=$quarter;}
if($kind==='rows'&&in_array($status,['matched','unmatched'],true)){$where.=' AND e.is_matched=?';$types.='i';$params[]=$status==='matched'?1:0;}
if($search!==''){$like='%'.$search.'%';$cols=['c.source_file','c.source_file_original_name','c.payment_register_file','c.payment_register_original_name','c.notes','c.uploaded_by','u.userName','u.userEmail'];$where.=' AND ('.implode(' OR ',array_map(fn($c)=>"COALESCE($c,'') LIKE ?",$cols)).')';foreach($cols as $_){$types.='s';$params[]=$like;}}
$from=' FROM tb_payroll_upload_cycles c LEFT JOIN tb_users u ON u.userId=c.uploaded_by'.($kind==='rows'?' INNER JOIN tb_payroll_upload_entries e ON e.cycle_id=c.cycle_id':'');
$countSql='SELECT COUNT(*) total,'.($kind==='rows'?'COALESCE(SUM(e.amount),0) total_amount':'0 total_amount').$from.$where;$s=$conn->prepare($countSql);bindPayrollHistoryParams($s,$types,$params);$s->execute();$tot=$s->get_result()->fetch_assoc()?:[];$s->close();$total=(int)($tot['total']??0);$pages=max(1,(int)ceil($total/$limit));$page=min($page,$pages);$offset=($page-1)*$limit;
$select=$kind==='cycles'?"c.cycle_id,c.payroll_year,c.payroll_month,c.financial_year_label,c.quarter_label,c.source_file_original_name,c.created_at,COALESCE(u.userName,'Unknown') uploaded_by_name":"e.entry_id,e.supplierNo,e.beneficiary_name,e.invoice_number,e.amount,e.matched_regNo,e.is_matched,c.payroll_year,c.payroll_month";$order=$kind==='cycles'?'c.created_at DESC':'e.entry_id DESC';$listParams=$params;$listParams[]=$limit;$listParams[]=$offset;$s=$conn->prepare("SELECT $select$from$where ORDER BY $order LIMIT ? OFFSET ?");bindPayrollHistoryParams($s,$types.'ii',$listParams);$s->execute();$rows=[];$r=$s->get_result();while($row=$r->fetch_assoc())$rows[]=$row;$s->close();echo json_encode(['success'=>true,'rows'=>$rows,'total'=>$total,'total_amount'=>(float)($tot['total_amount']??0),'page'=>$page,'total_pages'=>$pages]);$conn->close();
