<?php
declare(strict_types=1);

require_once __DIR__ . '/public_chat_common.php';

publicChatEnsureTables($conn);
publicChatRequireAgent($conn);
publicChatRequireCapability($conn, 'can_view_reports', 'You are not permitted to export public chat reports.');

$dateFrom = publicChatClean($_GET['date_from'] ?? '', 20);
$dateTo = publicChatClean($_GET['date_to'] ?? '', 20);
$district = publicChatClean($_GET['district'] ?? '', 120);
$category = publicChatClean($_GET['inquiry_category'] ?? '', 80);
$status = publicChatClean($_GET['status'] ?? '', 40);
$agent = publicChatClean($_GET['agent'] ?? '', 100);
$priority = publicChatClean($_GET['priority'] ?? '', 20);
$number = publicChatClean($_GET['number'] ?? '', 80);
$ticketStatus = publicChatClean($_GET['ticket_status'] ?? '', 40);

$where = [];
$types = '';
$params = [];

if ($dateFrom !== '') {
    $where[] = 'DATE(s.created_at) >= ?';
    $types .= 's';
    $params[] = $dateFrom;
}
if ($dateTo !== '') {
    $where[] = 'DATE(s.created_at) <= ?';
    $types .= 's';
    $params[] = $dateTo;
}
foreach ([
    's.district' => $district,
    's.inquiry_category' => $category,
    's.status' => $status,
    's.priority' => $priority,
    't.status' => $ticketStatus
] as $column => $value) {
    if ($value !== '') {
        $where[] = "{$column} = ?";
        $types .= 's';
        $params[] = $value;
    }
}
if ($agent !== '') {
    $where[] = 'u.userName LIKE ?';
    $types .= 's';
    $params[] = '%' . $agent . '%';
}
if ($number !== '') {
    $where[] = '(s.force_number = ? OR s.pensioner_number = ?)';
    $types .= 'ss';
    $params[] = $number;
    $params[] = $number;
}

$whereSql = $where ? ('WHERE ' . implode(' AND ', $where)) : '';
$sql = "
    SELECT s.chat_reference, s.visitor_name, s.phone_number, s.email, s.force_number, s.pensioner_number,
           s.district, s.location, s.inquiry_category, s.subject, s.status, s.priority,
           u.userName AS assigned_agent, s.created_at, s.first_response_at, s.closed_at, s.outcome,
           t.ticket_reference, t.status AS ticket_status
    FROM public_chat_sessions s
    LEFT JOIN tb_users u ON u.userId = s.assigned_agent_id
    LEFT JOIN public_chat_tickets t ON t.session_id = s.session_id
    {$whereSql}
    ORDER BY s.created_at DESC
    LIMIT 5000
";
$stmt = $conn->prepare($sql);
if (!$stmt) {
    publicChatJson(['success' => false, 'message' => 'Unable to prepare export.'], 500);
}
if ($types !== '') {
    $refs = [$types];
    foreach ($params as $i => $value) {
        $refs[] = &$params[$i];
    }
    call_user_func_array([$stmt, 'bind_param'], $refs);
}
$stmt->execute();
$rows = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt->close();

publicChatAudit($conn, null, 'Settings changed', ['export' => 'public_chat_report', 'filters' => $_GET]);

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="public_chat_report_' . date('Ymd_His') . '.csv"');
$out = fopen('php://output', 'w');
fputcsv($out, ['UPS PensionsGo - Public Live Chat Report']);
fputcsv($out, ['Generated', date('Y-m-d H:i:s')]);
fputcsv($out, ['Generated By', $_SESSION['userName'] ?? '']);
fputcsv($out, []);
fputcsv($out, ['Reference', 'Visitor', 'Phone', 'Email', 'Force No', 'Pensioner No', 'District', 'Location', 'Category', 'Subject', 'Status', 'Priority', 'Agent', 'Created', 'First Response', 'Closed', 'Outcome', 'Ticket Ref', 'Ticket Status']);
foreach ($rows as $row) {
    fputcsv($out, [
        $row['chat_reference'] ?? '',
        $row['visitor_name'] ?? '',
        $row['phone_number'] ?? '',
        $row['email'] ?? '',
        $row['force_number'] ?? '',
        $row['pensioner_number'] ?? '',
        $row['district'] ?? '',
        $row['location'] ?? '',
        $row['inquiry_category'] ?? '',
        $row['subject'] ?? '',
        $row['status'] ?? '',
        $row['priority'] ?? '',
        $row['assigned_agent'] ?? '',
        $row['created_at'] ?? '',
        $row['first_response_at'] ?? '',
        $row['closed_at'] ?? '',
        $row['outcome'] ?? '',
        $row['ticket_reference'] ?? '',
        $row['ticket_status'] ?? ''
    ]);
}
fclose($out);
?>
