<?php
header('Content-Type: application/json; charset=utf-8');require_once __DIR__.'/../config.php';if(session_status()===PHP_SESSION_NONE)session_start();
if(!isset($_SESSION['userId'])||!currentUserHasPermission($conn,'payroll.upload')){http_response_code(403);echo json_encode(['success'=>false,'message'=>'Access denied']);exit;}ensurePayrollManagementTables($conn);
$payload=json_decode(file_get_contents('php://input'),true)?:[];$target=strtolower(trim((string)($payload['target']??'')));$id=(int)($payload['id']??0);$decision=strtolower(trim((string)($payload['decision']??'')));$note=trim((string)($payload['note']??''));if($id<=0||!in_array($target,['classified','payment'],true)||!in_array($decision,['approve','reject','unapprove','unreject'],true)){http_response_code(422);echo json_encode(['success'=>false,'message'=>'Valid target, entry ID and decision are required']);exit;}
$isReversal=in_array($decision,['unapprove','unreject'],true);
if($target==='classified'){$status=$isReversal?'Pending Review':($decision==='approve'?'Approved':'Rejected');
    // A review decision never changes pensioner workflow state automatically.
    $sourceRowStmt=$conn->prepare('SELECT e.source_section,e.appeared_amount,e.reason,e.matched_regNo,e.cycle_id,c.payroll_year,c.payroll_month FROM tb_payroll_classified_entries e INNER JOIN tb_payroll_upload_cycles c ON c.cycle_id=e.cycle_id WHERE e.classified_entry_id=?');$sourceRowStmt->bind_param('i',$id);$sourceRowStmt->execute();$sourceRow=$sourceRowStmt->get_result()->fetch_assoc();$sourceRowStmt->close();
    $stmt=$conn->prepare('UPDATE tb_payroll_classified_entries SET review_status=?,reviewed_by=?,reviewed_at=NOW() WHERE classified_entry_id=?');$user=(string)$_SESSION['userId'];$stmt->bind_param('ssi',$status,$user,$id);
}else{$status=$isReversal?'Needs Review':($decision==='approve'?'Approved':'Rejected');$stmt=$conn->prepare('UPDATE tb_payroll_payment_register_entries SET review_status=?,review_note=CASE WHEN ?<>\'\' THEN ? ELSE review_note END WHERE register_entry_id=?');$stmt->bind_param('sssi',$status,$note,$note,$id);}
$stmt->execute();$affected=$stmt->affected_rows;$stmt->close();if($affected<1){http_response_code(404);echo json_encode(['success'=>false,'message'=>'Review entry was not found or unchanged']);exit;}
$arrearsResult=null;if($target==='classified'&&$decision==='approve'&&($sourceRow['source_section']??'')==='PENSION_ARREARS'&&trim((string)($sourceRow['matched_regNo']??''))!==''){$arrearsResult=upsertArrearsLedgerEntry($conn,['regNo'=>$sourceRow['matched_regNo'],'claim_type'=>'Pension Arrears','period_year'=>(int)$sourceRow['payroll_year'],'period_month'=>(int)$sourceRow['payroll_month'],'expected_amount'=>(float)$sourceRow['appeared_amount'],'reason'=>$sourceRow['reason']?:'Approved pension arrears payroll section entry.','notes'=>'Created only after authorized payroll-section review.','source_type'=>'payroll_section','reference_cycle_id'=>(int)$sourceRow['cycle_id'],'claim_status'=>'Incomplete','recorded_by'=>$_SESSION['userId']]);}
logPayrollAudit($conn,['action'=>'review_payroll_analysis_entry','actor_user_id'=>$_SESSION['userId'],'actor_role'=>$_SESSION['userRole']??'','details'=>['target'=>$target,'id'=>$id,'decision'=>$decision,'note'=>$note,'arrears_ledger_id'=>$arrearsResult['ledger_id']??null]]);$message=$isReversal?'The review decision was reverted and the item returned for review.':($arrearsResult?'Review approved and the pension arrears item was added to the arrears workflow.':'Review decision saved. No pensioner workflow state was changed automatically.');echo json_encode(['success'=>true,'message'=>$message,'arrears'=>$arrearsResult]);$conn->close();
