<?php
/**
 * 
 * export_user_logs.php
 * Purpose: Export user logs to CSV with enhanced display
 * Access: Admin only
 * 
 */

session_start();

// Verify admin access
if (!isset($_SESSION['userId']) || !sessionRoleIn($conn, ['admin'])) {
    http_response_code(403);
    header('Content-Type: application/json');
    echo json_encode([
        'success' => false,
        'message' => 'Admin access required'
    ]);
    exit;
}

// Fix the config path
require_once __DIR__ . '/../../config.php';

try {
    // Set CSV headers
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename=enhanced-user-logs-' . date('Y-m-d') . '.csv');

    // Get filter parameters
    $activityType = $_GET['activity_type'] ?? '';
    $dateFrom = $_GET['date_from'] ?? '';
    $dateTo = $_GET['date_to'] ?? '';
    $userName = $_GET['user_name'] ?? '';

    // Build query
    $query = "
        SELECT 
            log_id,
            user_id,
            user_name,
            user_role,
            activity_type,
            ip_address,
            user_agent,
            device_type,
            location,
            login_time,
            logout_time,
            duration_seconds,
            details,
            session_id,
            created_at
        FROM tb_user_logs
        WHERE 1=1
    ";

    $params = [];
    $types = '';

    if (!empty($activityType)) {
        $query .= " AND activity_type = ?";
        $params[] = $activityType;
        $types .= 's';
    }

    if (!empty($dateFrom)) {
        $query .= " AND DATE(created_at) >= ?";
        $params[] = $dateFrom;
        $types .= 's';
    }

    if (!empty($dateTo)) {
        $query .= " AND DATE(created_at) <= ?";
        $params[] = $dateTo;
        $types .= 's';
    }

    if (!empty($userName)) {
        $query .= " AND user_name LIKE ?";
        $params[] = '%' . $userName . '%';
        $types .= 's';
    }

    $query .= " ORDER BY created_at DESC";

    $stmt = $conn->prepare($query);
    
    if (!empty($params)) {
        $stmt->bind_param($types, ...$params);
    }

    $stmt->execute();
    $result = $stmt->get_result();

    // Create output stream
    $output = fopen('php://output', 'w');

    // Add BOM for UTF-8
    fputs($output, "\xEF\xBB\xBF");

    // 
    // User Logs Report Header //
    fputcsv($output, ['UPS PensionsGo - User Activity Logs Report']);
    fputcsv($output, ['Generated:', date('Y-m-d H:i:s')]);
    fputcsv($output, ['Generated by:', $_SESSION['userName'] ?? 'System Admin']);
    
    // Report filters
    fputcsv($output, ['FILTERS APPLIED:']);
    if (!empty($activityType)) {
        fputcsv($output, ['- Activity Type:', formatActivityType($activityType)]);
    }
    if (!empty($dateFrom)) {
        fputcsv($output, ['- Date From:', $dateFrom]);
    }
    if (!empty($dateTo)) {
        fputcsv($output, ['- Date To:', $dateTo]);
    }
    if (!empty($userName)) {
        fputcsv($output, ['- User Name Contains:', $userName]);
    }
    if (empty($activityType) && empty($dateFrom) && empty($dateTo) && empty($userName)) {
        fputcsv($output, ['- No filters applied (showing all records)']);
    }
    
    fputcsv($output, ['']); // Empty row

    // 
    // Summary Statistics Section //
    fputcsv($output, ['SUMMARY STATISTICS']);
    
    // Get total count
    $totalQuery = "SELECT COUNT(*) as total FROM tb_user_logs";
    $totalResult = $conn->query($totalQuery);
    $totalData = $totalResult->fetch_assoc();
    
    // Get filtered count
    $filteredCount = $result->num_rows;
    
    fputcsv($output, ['Total Records in System:', $totalData['total'] ?? 0]);
    fputcsv($output, ['Records in This Export:', $filteredCount]);
    fputcsv($output, ['Export Date Range:', $dateFrom . ' to ' . ($dateTo ?: 'Current')]);
    
    // Get activity breakdown for filtered results
    if (!empty($params)) {
        $breakdownQuery = str_replace("ORDER BY created_at DESC", "GROUP BY activity_type ORDER BY COUNT(*) DESC", $query);
        $breakdownStmt = $conn->prepare($breakdownQuery);
        if (!empty($params)) {
            $breakdownStmt->bind_param($types, ...$params);
        }
        $breakdownStmt->execute();
        $breakdownResult = $breakdownStmt->get_result();
        
        fputcsv($output, ['Activity Breakdown:']);
        while ($breakdown = $breakdownResult->fetch_assoc()) {
            fputcsv($output, ['- ' . formatActivityType($breakdown['activity_type']) . ':', $breakdown['count'] ?? 0]);
        }
        $breakdownStmt->close();
    }
    
    fputcsv($output, ['']); // Empty row

    // 
    // Detailed Logs Section //
    fputcsv($output, ['DETAILED ACTIVITY LOGS']);
    fputcsv($output, ['']); // Empty row
    
    fputcsv($output, [
        'S/N',
        'LOG ID',
        'TIMESTAMP',
        'USER ID',
        'USER NAME',
        'USER ROLE',
        'ACTIVITY TYPE',
        'IP ADDRESS',
        'DEVICE TYPE',
        'LOCATION',
        'LOGIN TIME',
        'LOGOUT TIME',
        'DURATION (SECONDS)',
        'DURATION (FORMATTED)',
        'SESSION ID',
        'USER AGENT',
        'DETAILS'
    ]);

    // Data rows with Enhanced Export Display
    $serial = 1;
    while ($row = $result->fetch_assoc()) {
        // Enhanced user name handling
        $userName = $row['user_name'] ?? 'Unknown';
        if ($userName === 'Unknown User' || empty($userName)) {
            $userName = 'System User';
        }
        
        // Enhanced IP address handling (using same logic as config.php)
        $ipAddress = $row['ip_address'] ?? '::1';
        if ($ipAddress === '::1') {
            $ipAddress = 'Localhost (127.0.0.1)';
        }
        
        // Enhanced activity type formatting
        $activityType = $row['activity_type'] ?? 'N/A';
        $formattedActivity = formatActivityType($activityType);
        
        // Enhanced device type
        $deviceType = $row['device_type'] ?? 'Unknown';
        if ($deviceType === 'Unknown') {
            $deviceType = 'Not Detected';
        }
        
        // Enhanced location
        $location = $row['location'] ?? 'N/A';
        if ($location === 'N/A' || empty($location)) {
            $location = 'Not Available';
        }
        
        // Format duration - FIXED: Remove $this->
        $durationSeconds = $row['duration_seconds'] ?? 0;
        $formattedDuration = formatDuration($durationSeconds);
        
        // Enhanced details
        $details = $row['details'] ?? 'No details';
        if (empty($details) || $details === 'null') {
            $details = 'No additional details';
        }

        fputcsv($output, [
            $serial++,
            $row['log_id'] ?? 'N/A',
            $row['created_at'] ?? 'N/A',
            $row['user_id'] ?? 'N/A',
            $userName,
            $row['user_role'] ?? 'N/A',
            $formattedActivity,
            $ipAddress,
            $deviceType,
            $location,
            $row['login_time'] ?? 'N/A',
            $row['logout_time'] ?? 'N/A',
            $durationSeconds,
            $formattedDuration,
            $row['session_id'] ?? 'N/A',
            $row['user_agent'] ?? 'Not Available',
            $details
        ]);
    }

    fputcsv($output, ['']); // Empty row
    fputcsv($output, ['--- END OF UPS PensionsGo REPORT ---']);
    fputcsv($output, ['Note:', 'IP addresses are formatted using system-wide detection logic']);
    fputcsv($output, ['Total Records Exported:', $filteredCount]);

    fclose($output);
    $stmt->close();

} catch (Exception $e) {
    header('Content-Type: application/json');
    echo json_encode([
        'success' => false,
        'message' => 'Export failed: ' . $e->getMessage()
    ]);
}

/**
 * Format duration in seconds to human readable format
 * FIXED: Removed $this-> reference
 */
function formatDuration($seconds) {
    if ($seconds === 0 || $seconds === null) {
        return 'N/A';
    }
    
    if ($seconds < 60) {
        return $seconds . ' sec';
    } elseif ($seconds < 3600) {
        $minutes = floor($seconds / 60);
        $remainingSeconds = $seconds % 60;
        return $minutes . ' min ' . $remainingSeconds . ' sec';
    } else {
        $hours = floor($seconds / 3600);
        $minutes = floor(($seconds % 3600) / 60);
        return $hours . ' hr ' . $minutes . ' min';
    }
}

/**
 * Format activity type for better readability
 */
function formatActivityType($activityType) {
    $formatted = str_replace('_', ' ', $activityType);
    return ucwords($formatted);
}

$conn->close();
?>
